### ISSUE TITLE
Challenge editor: adding decorations throws string format exception

### ISSUE THREAD

**Issue by EclipseKnight** [nyirsh/MH3P-CQE#2]
Hey Nyirsh, 

I reached out on discord about this issue. It's been a while since you've helped us out and since then a good amount of progress has been made on the remake, just very slowly. 

I ran into an issue once again when trying to add decorations to challenge sets. 

![image](https://user-images.githubusercontent.com/32472185/102718329-93232580-42b5-11eb-98dc-e6a3026bd9f1.png)

Even opening existing challenge quests yield no results

![image](https://user-images.githubusercontent.com/32472185/102718337-a0401480-42b5-11eb-9618-6a09a99947a1.png)

I was curious if you would be able to help us resolve this, or if you had the source code for the fixed version you did for us then it would be awesome to get that or an updated git repo. 

Thanks in advance!

**Comment by nyirsh** [comment]
Sooo turned out to be an issue related to the decorations translations file. Gonna make a better version of this stuff one day!
